name: Fetch Dune Items

on:
  schedule:
    # Runs daily at 02:07 UTC
    - cron: "7 2 * * *"
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
    paths:
      - '.github/workflows/fetch.yml'

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          
      - name: Create output directory
        run: mkdir -p public/api
        
      - name: Fetch English items
        run: |
          echo "Fetching English data..."
          curl -fsSL "https://dune-api.gaming.tools/items?lang=en" \
            -H "User-Agent: dune-cache-gh-actions" \
            -H "Accept: application/json" \
            --retry 5 \
            --retry-delay 3 \
            -o "public/api/items.en.json"
          
          # Validate JSON
          jq -e . "public/api/items.en.json" > /dev/null
          echo "✓ English data fetched successfully"
          
      - name: Fetch Ukrainian items
        run: |
          echo "Fetching Ukrainian data..."
          curl -fsSL "https://dune-api.gaming.tools/items?lang=uk" \
            -H "User-Agent: dune-cache-gh-actions" \
            -H "Accept: application/json" \
            --retry 5 \
            --retry-delay 3 \
            -o "public/api/items.uk.json"
          
          # Validate JSON
          jq -e . "public/api/items.uk.json" > /dev/null
          echo "✓ Ukrainian data fetched successfully"
          
      - name: Fetch Russian items
        run: |
          echo "Fetching Russian data..."
          curl -fsSL "https://dune-api.gaming.tools/items?lang=ru" \
            -H "User-Agent: dune-cache-gh-actions" \
            -H "Accept: application/json" \
            --retry 5 \
            --retry-delay 3 \
            -o "public/api/items.ru.json"
          
          # Validate JSON
          jq -e . "public/api/items.ru.json" > /dev/null
          echo "✓ Russian data fetched successfully"
          
      - name: Generate metadata
        run: |
          TIMESTAMP=$(date -u +%FT%TZ)
          
          # Create metadata for each language
          for lang in en uk ru; do
            echo "{
              \"last_updated\": \"$TIMESTAMP\",
              \"source\": \"https://dune-api.gaming.tools/items?lang=$lang\",
              \"language\": \"$lang\"
            }" | jq . > "public/api/meta.$lang.json"
          done
          
          # Create main index
          echo "{
            \"last_updated\": \"$TIMESTAMP\",
            \"repository\": \"${{ github.repository }}\",
            \"api_source\": \"https://dune-api.gaming.tools\",
            \"reference\": \"https://dune.gaming.tools/\",
            \"available_languages\": [\"en\", \"uk\", \"ru\"],
            \"files\": {
              \"en\": \"/api/items.en.json\",
              \"uk\": \"/api/items.uk.json\",
              \"ru\": \"/api/items.ru.json\"
            }
          }" | jq . > "public/index.json"
          
      - name: Create simple index.html
        run: |
          cat > public/index.html << 'ENDOFFILE'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Dune Awakening API Cache</title>
              <style>
                  body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                  h1 { color: #333; }
                  .links { margin: 20px 0; }
                  .links a { display: block; margin: 10px 0; color: #0066cc; }
                  code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }
              </style>
          </head>
          <body>
              <h1>Dune Awakening API Cache</h1>
              <p>Cached mirror of the Dune Awakening Gaming Tools API</p>
              <p>Reference: <a href="https://dune.gaming.tools/">https://dune.gaming.tools/</a></p>
              
              <div class="links">
                  <h2>Available Data:</h2>
                  <a href="/api/items.en.json">English Items (items.en.json)</a>
                  <a href="/api/items.uk.json">Ukrainian Items (items.uk.json)</a>
                  <a href="/api/items.ru.json">Russian Items (items.ru.json)</a>
                  <br>
                  <a href="/index.json">Index with metadata (index.json)</a>
              </div>
              
              <div>
                  <h2>Usage:</h2>
                  <code>https://beromario.github.io/dune-awakening-api.gaming.tools-cache/api/items.uk.json</code>
              </div>
          </body>
          </html>
          ENDOFFILE
          
      - name: List generated files
        run: |
          echo "Generated files:"
          ls -la public/
          ls -la public/api/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
